const Pressure_vs_depletion = [
    {
        pressure:10,
        clay:0,
        loam:0,
        sandyLoam:0,
        fineSandyLoam:0,
        loamySand:0
    },
    {
        pressure:20,
        clay:5,
        loam:8,
        sandyLoam:29,
        fineSandyLoam:36,
        loamySand:41
    },
    {
        pressure:30,
        clay:8,
        loam:15,
        sandyLoam:42,
        fineSandyLoam:50,
        loamySand:56
    },
    {
        pressure:40,
        clay:12,
        loam:22,
        sandyLoam:50,
        fineSandyLoam:57,
        loamySand:64
    },
    {
        pressure:50,
        clay:15,
        loam:30,
        sandyLoam:55,
        fineSandyLoam:63,
        loamySand:71
    },
    {
        pressure:60,
        clay:18,
        loam:37,
        sandyLoam:60,
        fineSandyLoam:66,
        loamySand:75
    },
    {
        pressure:70,
        clay:20,
        loam:44,
        sandyLoam:62,
        fineSandyLoam:70,
        loamySand:78
    },
    {
        pressure:80,
        clay:23,
        loam:50,
        sandyLoam:65,
        fineSandyLoam:72,
        loamySand:79
    },
    {
        pressure:90,
        clay:26,
        loam:52,
        sandyLoam:67,
        fineSandyLoam:74,
        loamySand:80
    },
    {
        pressure:100,
        clay:29,
        loam:55,
        sandyLoam:68,
        fineSandyLoam:74,
        loamySand:82
    },
    
];
  
module.exports = { data: Pressure_vs_depletion };